[package]
name = "kazi-escrow"
version = "0.1.0"
edition = "2021"
description = "Kazi Trust escrow smart contract for Stellar Soroban"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "0.11"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
